# Generated by Django 4.1 on 2023-06-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0005_alter_user_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="maximum_marks",
            field=models.DecimalField(decimal_places=2, default=4, max_digits=6),
        ),
    ]
