# Generated by Django 4.1 on 2023-06-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0007_quiz_total_marks"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentanswer",
            name="is_correct",
            field=models.BooleanField(default=False, verbose_name="Correct answer"),
        ),
    ]
