# Generated by Django 4.1 on 2023-06-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0008_studentanswer_is_correct"),
    ]

    operations = [
        migrations.RemoveField(model_name="studentanswer", name="is_correct",),
    ]
