# Generated by Django 4.1 on 2023-06-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0009_remove_studentanswer_is_correct"),
    ]

    operations = [
        migrations.RemoveField(model_name="question", name="maximum_marks",),
    ]
