# Generated by Django 4.1 on 2023-06-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0011_alter_answer_id_alter_question_id_alter_quiz_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="takenquiz", name="score", field=models.IntegerField(null=True),
        ),
    ]
