# Generated by Django 4.1 on 2023-10-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0012_alter_takenquiz_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="Img",
            field=models.ImageField(
                null=True,
                upload_to="C:/Users/Aryan/Quizou_Website/images",
                verbose_name="Question",
            ),
        ),
    ]
